//! gRPC schema shared by the daemon and its clients (spec §I, Slice S11).
#![forbid(unsafe_code)]

/// Generated messages and services.
///
/// The module is generated by `tonic-prost-build`, so the workspace's
/// documentation and visibility lints do not apply to it.
#[allow(missing_docs, unreachable_pub, clippy::all, clippy::pedantic)]
pub mod v1 {
    tonic::include_proto!("linuxreflect.v1");
}
